### ISSUE TITLE
shell not re-enabled on renew of account

### ISSUE THREAD

**Issue by butlerx** [redbrick/useradm#3]
if the user's shell is /usr/local/shell/expired and is renewed, shell isn't reset to /usr/local/shell/zsh

**Comment by rbkoffee** [comment]
[useradm renew resetpw](https://github.com/redbrick/useradm/blob/252b39fbc87e74e0b5a4734f6c7125f583c74249/useradm/useradm.py#L455-L456)

Issue should be against these lines; set the default shell to /usr/local/shells/zsh 
The currenvt invocation of this flag just resets to /usr/local/shell/&current_shell

**Comment by butlerx** [comment]
closed in #14
