### ISSUE TITLE
unable to renew usertype associate to member

### ISSUE THREAD

**Issue by butlerx** [redbrick/useradm#4]
if renewing && usertype is associat/committe it will hint at restoring usertype to member
- For committe this wouldn't be as bad, but for associat this poses an issue frequently.

**Comment by zergless** [comment]
do you have an example? this has worked for me in the past

**Comment by butlerx** [comment]
i don't remember since this has worked since but for certain users it didn't

**Comment by zergless** [comment]
I think closing it for now is fine. Its worked for me since then. can be reopened if needed
