### ISSUE TITLE
Pylint Errors

### ISSUE THREAD

**Issue by GoldenBadger** [redbrick/useradm#6]
So I ran `pylint` on useradm out of curiosity. I suppose a good start to cleaning up the repo would be to fix these errors. The output is too long to paste into this issue so I've attached it here: [pylint.txt](https://github.com/redbrick/useradm/files/587412/pylint.txt). Fixing these errors will be a fantastic start to cleaning up the repo.

**Comment by butlerx** [comment]
updated lint https://gist.github.com/butlerx/a7cc82ccb5b40a4e3d02c87c26769a58

**Comment by VoyTechnology** [comment]
Update: we are now tracking the python linting problems using CodeClimate.

**Comment by butlerx** [comment]
just as an fyi pylint has become disabled on codeclimate a `.codeclimate` file should be added 
#26 should fix this
